import React from "react"

const Research_4 = () => {
    return (
        <div>
            <h1>Watermelon variety improvement through conventional breeding and tissue culture</h1>
            <h2>12 July 2021 - BIO Engineering (Dr. Phat Phanna)</h2>
            <p><strong>Introduction</strong>:Despite having favorable conditions for the year-round production of watermelon and good demand in the world market, less efforts have been made to breed and produce high quality watermelon in Cambodia, especially the high cost seedless watermelon resulting from a crossing of tetraploid and diploid. This project intends to produce OP varieties of diploid and tetraploid watermelon with improved traits such as, high yield, desired rind colors, excellent flesh colors, and high soluble solids for commercial production in the high end market. The improved seeds from this project will be registered and disseminated to collaborative partners and watermelon growers for commercial production with a cultivating guide book. The success of this activity will lead to new era of watermelon seed industry in Cambodia and future seed supply in nationwide and exporting produces to the international market with the promise of premium quality and prices.
                Because horticultural crops could contribute substantially to poverty alleviation, Royal Government of Cambodia has set a clear strategy on increasing productivity, diversification and commercialization of horticultural produces (MAFF, 2017). Achieving this strategy requires advanced horticultural research focusing on variety improvement, commercial seed production and safe production systems. Watermelon (Citrulus lanatus) is among horticultural crops widely grown in Cambodia in both uplands and lowlands as a cash crop and can be intercropped or grown before or after rain-fed lowland rice and suitable for incorporating in agroforestry. Up to now, watermelon varietal improvement in Cambodia have been initiated with two released varieties by Cambodian Agricultural Research and Development Institute (CARDI) in 2001 and ended in 2006, while more than 1200 varieties which are varied with shape and color have been grown in many regions of the world. And the two red flesh varieties have not been well adopted by the farmers as the markets preferred introduced hybrids with high yield, popular flesh color with high sugar content. This project aim to produce new diploid and tetraploid varieties with high yield and quality such as, high sugar content, good shelf life, excellent flesh colors (yellow and red) and good shapes and register as National New Varieties Release, and provide seeds to forest community, industrial partners for commercial production.</p>
            <p><strong>The specific objectives of this research are:</strong>
                <ul>
                    <li>
                        To collect and characterize indigenous and introduced varieties collected for identification of genetic resources associated with beneficial traits for use in breeding programs                    </li>
                    <li>
                        To improve watermelon varieties through pedigree breeding for selection of high yield and high quality OP varieties and new parents for seeded hybrids                    </li>
                    <li>
                        To optimize tissue culture conditions using aqueous colchicine at different concentration levels for optimizing tetraploid induction, a prerequisite to the production of seedless hybrids, and screening for improved varieties according to somaclonal variations                    </li>
                    <li>
                        To share the outputs of the 5 OP varieties with forest community and industrial partner and develop diploid and triploid hybrids
                    </li>
                </ul>
            </p>
            <p><strong>Hypothesis</strong>: Within a wide collection of both indigenous and introduced varieties, the high quality and yield of introduced varieties and well adaptability of wild/indigenous varieties collected will be substantial for new varietal development. Five new open pollinated varieties with traits of interests such as, excellent flesh and rind color, long shelf life, high soluble solids and high yield would successfully produce through pedigree selection breeding and ten lines of tetraploids will produced through plant tissue culture with/without application of colchicine, a chemical agent induced chromosome doubling.
            </p>
            <p><strong>Methodology</strong>:11 provinces include Kandal, Kampong cham, Kratie, Stoeng treng, Mondulkiri, Ratanakiri, Preah Vihear, Kampongthom, Siem Reap, Battambang, and Banteay Meanchey will be assigned for seed collections of both indigenous and introduced varieties. The examination of distinctness, uniformity and stability and production of harmonized variety descriptions according to UPOV guidelines will be conducted. Varieties with potential agronomic traits such as, high yield, long shelf life, high soluble solids with yellow, orange, or red flesh color, or adaptable to Cambodian climate will be used in pedigree selection breeding, whereby two parents are crossed to produce an F1 which later are repeated self-pollinating or sib mating for selection of the best line from generation to generation which ultimately at the advanced inbreeding, the best lines (F6/F7) are tested for potential release as new OP varieties or new parents for hybrids. Measurements of fruit yield and quality will be fruit weight, length, and diameter, hollowheart, rind pattern, flesh color and soluble solids. Uniform and homogenous varieties with high yield and quality according to the first screening and F4-F6 derived from pedigree breeding will be germinated in in vitro for excising of cotyledon for culturing on MS medium supplemented with 1mg/l BAP and 0.1mg/l IAA to initiate adventitious calli and treated without/with aqueous colchicine at different levels (0, 0.1%, 0.2%, 0.5%) to induce somaclonal variants showing superior or tetraploid traits. Morphological characteristics and number of chloroplasts in stomata will be used as indicators for discrimination between diploids and tetraploids. Diploid somaclonal variants, F5 and F6 generation derived from pedigree breeding which become uniform and homogeneous and show superior traits will be further evaluated in trials and do seed increase, register as new open pollinated varieties and disseminated to collaborative partners,  whereas tetraploids will be proposed for producing triploid hybrids for production of seedless watermelon. The statistical analysis will be performed using analysis of variances (ANOVA).
            </p>
            <p><strong>Expected Results</strong>: We expect to produce at least 5 open pollinated varieties with high yield, long shelf life, high soluble solids with yellow, orange, or red flesh color and adaptable to Cambodian climate, which potentially for registration as National New Variety Release and disseminate to forestry community and industrial partners. We expect to use tetraploids and diploids from this project for producing diploid and triploid hybrids which are premium quality with industrial partner and issue patents for commercialization. We expect to produce three graduate thesis, 4 undergraduate, 1 article in international peer-reviewed journal and 2 articles in national peer-reviewed journal, and one watermelon breeding book.</p>
        </div>
    )
}

export default Research_4;