import React from "react";

export const Research_6 = () =>
{
    return(
        <>
            <h1>A New Model for Simulating and Evaluating Congestion Cause at Signalized Intersection</h1>
            <h2>June 2019 - Information Technology Engineering (Sokchea Kor and Susanne Krömker) </h2>
            <h3>Overview</h3>
            <p>This paper presents a simulation framework to determine congestion cause for an isolated signalized intersection having four-approaches with through and left-right turn movement under homogenous condition. The simulation framework consists of various correlated models such as vehicles’ path model, car following model, vehicles’ arrival model, and evaluation model. The framework is then implemented to create SPSV (Special Purpose Simulation and Visualization) software. These models are presented in mathematical terms with specified parameters and objective function that later are interrupted and discretized using Object-oriented methodology with programming language. The vehicles’ path model is a piecewise function describing a driver’s position when approaching intersection till leaving intersection in terms of time. The vehicle arrival model is based on negative exponential distribution. The data generated by the models will be used to evaluate the traffic performance on the specified scenario. The parameters input to the models will be used to suggest the optimal setting to determine the factors for better intersection performance.</p>
            <p>
                <strong className={"important"}>
                    This paper got outstanding paper award at ICONI 2018
                </strong>
            </p>
        </>
    )
}